services:
  - docker

env:
  global:
    - IMAGE_NAME=diuis/docker-debian9-git_wget

script:
  - docker build . -t "$IMAGE_NAME"

before_deploy:
  - docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master